---
title: "complaints DAG"
format: html
editor: visual
---

## Complaint Process DAG

**Inciting incident**

-   financial institution errors
-   life events
-   financial mismanagement
-   third parties (fraud, financial abuse, merchant stuff)

**Company behavior**

-   customer service
-   resolution direction (relief or no relief)
-   appropriateness of resolution (consumer is defrauded of a large sum, but only gets overdraft refunded)
-   quality of communication
-   non-customer service delays
-   company behavior is impacted by regulations

**Consumer motivations to complaint**

-   monetary stakes
-   other stakes (stay in home)
-   voice (want to change the companies policy)
    -   revenge - want to damage the company
    -   justice - want the company to do the right thing
-   control information collection/sharing/use
    -   consumer wants to control data and use of data
-   consumer understanding of legal rights
-   past experience complaining
-   perceived likelihood of success? (Self efficacy?)

How does this manifest though? All of these things contribute to some concept like "persistence"

**Consumer search**

-   internet search
-   social search
-   IRL social interaction
-   CFPB marketing
-   third parties and third party marketing (Credit repair, lawyer, etc)

Consumer then weighs one or more options and determines which one fits with motivation.

**Barriers to submission**

-   language
    -   comprehension
    -   fluency
-   time burden
-   context (landing pages, explanation)

Can we write down a dag for this?

```{r}

library(ggdag)
library(ggplot2)
theme_set(theme_dag())



coords <- tibble::tribble(
  ~name,  ~x,  ~y
  , "U",  1,   3  
  , "bank_error", 2, 3
  , "events", 2, 2
  , "third_party", 2, 4 
  , "legal_framework", 4, 3
  , "problem_resolution", 5, 3
  , "search_mediators",  6, 3
  , "complaint_submission", 7, 3
  , "persistance", 3, 5
  , "financial_situation", 2, 4
  , "stakes", 3, 4
  , "problem", 3, 3
)

complaining_dag <- dagify(
  complaint_submission ~ search_mediators
  , search_mediators ~  problem_resolution + persistance 
  , problem ~ financial_situation + bank_error + third_party + events 
  , problem_resolution ~ financial_situation + third_party + 
    persistance + legal_framework
  , legal_framework ~ problem
  , financial_situation ~ events + bank_error + U 
  , stakes ~ financial_situation
  , persistance ~ stakes + legal_framework
  , problem_resolution ~ stakes 
  , events ~ third_party
  , labels = c(
    "complaint_submission" = "Submission of complaint"
    , "financial_situation" = "Financial Situation"
    , "problem" = "Problem to solve"
    , "third_party" = "Third Party Causes"
    , "events" = "Unfortunate Events"
    , "problem_resolution" = "FI Resolution"
    , "persistance" = "Persistance/self-efficacy"
    , "bank_error" = "FI Error"
    , "search_mediators" = "Search process"
    , "legal_framework" = "Legal Framework"
    , "stakes" = "Consumer Stakes"
    , "U" = "U"
    )
  , coords = coords
)

ggdag(complaining_dag, text = FALSE, use_labels = "label")

```

How can we simulate this? Do we need to something agent based? (That seems really hard.) Maybe ask travis/rebecca if they have any familiarity. Maybe some of the econ people do stuff like that?



